# Webserver configs
server:
  port: 8086
  servlet:
    contextPath: /api/order

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 10
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    password: password
    url: jdbc:postgresql://localhost:5432/order_db
    user: admin
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-consumers
      value-deserializer: com.ecommerce.sdk.serdes.deserializer.PlaceOrderKafkaDeserializer

logging:
  level:
    org:
      springframework:
        security: DEBUG