spring:
  datasource:
    url: jdbc:postgresql://buyer-db:5432/buyer_db
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    url: jdbc:postgresql://buyer-db:5432/buyer_db
  kafka:
    bootstrap-servers: kafka-broker:9092

keycloak:
  auth-server-url: http://auth-keycloak:8080/auth
