# Webserver configs
server:
  port: 8082
  servlet:
    contextPath: /api/buyer

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buyer_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 10
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    password: password
    url: jdbc:postgresql://localhost:5432/buyer_db
    user: admin
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: buyer-consumers
      value-deserializer: com.ecommerce.sdk.serdes.deserializer.PlaceOrderBuyerKafkaDeserializer

keycloak:
  realm: buyer-realm
  resource: buyer-service
  auth-server-url: https://localhost/auth
  ssl-required: external
  credentials:
    secret: 4f8570d4-459d-4652-a046-3db396642465
  use-resource-role-mappings: false

logging:
  level:
    org:
      springframework:
        security: DEBUG